clusterpedia-io/client-go

- client/client.go
- constants/constants.go
- examples/list-clusterpedia-resources/main.go
add function to get a client for clusterpedia.
> add function to get a client for clusterpedia.

- client/client.go
- examples/list-clusterpedia-resources/main.go
- fake/fake_client.go
- fake/fake_pod_test.go
- fake/typed/pod/v1/fake_pod.go
- go.mod
- tools/builder/options.go
update the module name to `github.com/clusterpedia-io/client-go`
update the go version to `1.16`
> update the module name and go version

- go.mod
- go.sum
> cleanup mod

- constants/constants.go
- examples/list-clusterpedia-resources/main.go
- fake/fake_pod_test.go
- fake/typed/pod/v1/fake_pod.go
- tools/builder/options.go
- tools/builder/options_test.go
* fix the listOption build logic
* add labelSelector `SearchLabelWithRemainingCount`
> fix listOptions build logic

- constants/constants.go
- tools/builder/options.go
add FieldSelector,LabelSelector:Owners,OwnerSeniority
> add FieldSelector,LabelSelector:Owners,OwnerSeniority

- client/client.go
set `defaultQPS` and `defaultBurst`
> set defaultQPS and defaultBurst

- dynamic/client.go
For the crd resources, we shoulid provide dynamic client.
Signed-off-by: calvin <wen.chen@daocloud.io>
> add dynamic client

- fake/storage/memory/storage.go
> labelselect and page limit

- fake/storage/memory/storage.go
Signed-off-by: huoyinghao <962917302@qq.com>
> update ownerid select

- fake/kubeapiserver/resource_handler.go
skip checking the cluster data.
> fixed get request

- fake/kubeapiserver/pediaClusterTemp.go
fix rolebindings spelling mistakes
> fix rolebindings spelling mistakes

- customclient/interface.go
- customclient/scheme.go
- customclient/simple.go
- examples/custom-client/main.go
add custom client for params and raw sql
> add custom client

- constants/constants.go
- tools/builder/options.go
update search label, add search by owner-name
> update search label

- fake/kubeapiserver/pediaClusterTemp.go
> add gvr for hpa

- fake/storage/memory/storage.go
Signed-off-by: huoyinghao <962917302@qq.com>
> add fieldselector

- fake/storage/memory/storage.go
Signed-off-by: huoyinghao <962917302@qq.com>
> add ownername select

- constants/constants.go
- tools/builder/options.go
Signed-off-by: RuliXu <lily.xu@daocloud.io>
> Add Fuzzy Name Search

- fake/kubeapiserver/pediaClusterTemp.go
> add kubeanclusterops crd

- tools/builder/options.go
- tools/builder/options_test.go
> add k8s native selector

- clusterpediaclient/v1beta1/collectionresource.go
Fetch do not return error correctly
> Fetch do not return error correctly

- clusterpediaclient/v1beta1/collectionresource.go
> add timeout option in Fetch

- tools/builder/options.go
add TimeoutSeconds method in listOptions
> add TimeoutSeconds method in listOptions

- tools/builder/options.go
fix Timeout method in listOptions
> fix Timeout method in listOptions
